repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/PyCQA/isort
  rev: 5.9.3
  hooks:
  - id: isort
    args: [ "--profile", "black", "--filter-files" ]
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
- repo: https://gitlab.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      args: [ "--config", ".flake8" ]
      additional_dependencies: [ "flake8-quotes" ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
    - id: mypy
